{% set name = "curio" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57edce81c837f3c2cf42fbb346dee26e537d1659e6605269fb13bd179e068744

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
    - examples
  requires:
    - pytest
    - python {{ python_min }}
  imports:
    - {{ name }}
  commands:
    - pytest --ignore tests/test_socket.py --ignore tests/test_sync.py
    - pip check

about:
  home: https://curio.readthedocs.org/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: The coroutine concurrency library.
  description: |
    Curio is a library for performing concurrent I/O and common system programming
    tasks such as launching subprocesses and farming work out to thread and process
    pools. It uses Python coroutines and the explicit async/await syntax introduced
    in Python 3.5. Its programming model is based on cooperative multitasking and
    existing programming abstractions such as threads, sockets, files, subprocesses,
    locks, and queues. You'll find it to be small and fast.
  doc_url: https://curio.readthedocs.org/
  dev_url: https://github.com/dabeaz/curio

extra:
  recipe-maintainers:
    - scopatz
    - jochym
    - synapticarbors
