{% set name = "curio" %}
{% set version = "1.1" %}
{% set hash = "2a80008769066a8adac45adde90520156fc727e9169a55b2dc40a22a7f3e871c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  source_files:
    - tests
    - examples
  requires:
    - pytest
  imports:
    - {{ name }}
  commands:
    - pytest --ignore tests/test_socket.py --ignore tests/test_sync.py

about:
  home: https://curio.readthedocs.org/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: The coroutine concurrency library.
  description: |
    Curio is a library for performing concurrent I/O and common system programming
    tasks such as launching subprocesses and farming work out to thread and process
    pools. It uses Python coroutines and the explicit async/await syntax introduced
    in Python 3.5. Its programming model is based on cooperative multitasking and
    existing programming abstractions such as threads, sockets, files, subprocesses,
    locks, and queues. You'll find it to be small and fast.
  doc_url: https://curio.readthedocs.org/
  dev_url: https://github.com/dabeaz/curio

extra:
  recipe-maintainers:
    - scopatz
    - jochym
