{% set name = "curio" %}
{% set version = "0.7" %}
{% set sha256 = "95aa81842241848ccd93717d0a02a51d8c5623543944cea3c58a7ba757b0e436" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://github.com/dabeaz/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
  commands:
    - cd "${SRC_DIR}"
    - pytest

about:
  home: https://curio.readthedocs.org/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The coroutine concurrency library.'
  description: |
    Curio is a library for performing concurrent I/O and common system programming
    tasks such as launching subprocesses and farming work out to thread and process
    pools. It uses Python coroutines and the explicit async/await syntax introduced
    in Python 3.5. Its programming model is based on cooperative multitasking and
    existing programming abstractions such as threads, sockets, files, subprocesses,
    locks, and queues. You'll find it to be small and fast.
  doc_url: https://curio.readthedocs.org/
  dev_url: https://github.com/dabeaz/curio

extra:
  recipe-maintainers:
    - scopatz
