appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: ZCe7z4wRcNzDSWL+0RHIuUnKN5ovX/g87skuZZm65eWLTvAio2rz5wkGyZZxtV52WIBKLTDh+GAAIa2fBYa4WtE/frEN6HGxM0LgVBBmMXedHeLBz8yUlsijhvlQA+Sfc9pRc7MlNH1vEJzCxeQfiMpzuHYsi0k7/UCJfY5ZOecyTcN9J7Sq0luI4+yA7PTfBpNIv2OqpdHIpyfgy7IM19my9PlmqSpUbvBSOaKENHz5QMd0/TISZFIF744lhCJPGuqu/o1Pqlt7Z1nK5T/3DNh7ooW93qT2H5an2E9KYyx9tnclV7dXkl1HdFtXrW/AzkCXx8izuug3DoktFolsuqXg/Jt+dSqhgv7JP088krqO7OtIHaMshXbZmFFQAMAH+CgizImUgmh4oMjDk79fl0tyEic3Jrwj92c/zwNXIUbdI/LATg/RV7AkyB0TDK0o6jTdtMmjpPs6Pk+c/yznwKoM6W86/gjeeUMV7fQfu1B+a34jxjtzOp3BAf/lf6Qj1zszEB52viPJ+zAgyESd6vILrKdjRWGhPYtov1ocOSASTqYnrUDIaz3FC53oi6vAg4rMqJRMZBfr7B78pvTZQ68qofKZ4e2GNPDWpsaG2Q6EyQBzSc2WaAnVoum/i6v9SPp0l86aIavqHkWMGQDWsCJt2c0euT6zvBsJNojj+QM=}
bot:
  automerge: true
conda_forge_output_validation: true
